### ISSUE TITLE
Error post "npm run build"

### ISSUE THREAD

**Issue by tausif-bi** [Uniswap/smart-order-router#102]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

getting below error : 

C:\Users\smart-order-router-main>npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> @uniswap/smart-order-router@2.5.30 build
> run-p compile-v3-types compile-v2-types compile-router compile-external-types && run-p build:*

> @uniswap/smart-order-router@2.5.30 compile-external-types
> npx typechain --target ethers-v5 --out-dir src/types/other 'src/abis/**/*.json'

> @uniswap/smart-order-router@2.5.30 compile-v3-types
> npx typechain --target ethers-v5 --out-dir src/types/v3 './node_modules/@uniswap/?(v3-core|v3-periphery)/artifacts/contracts/**/*.json'

> @uniswap/smart-order-router@2.5.30 compile-router
> npx typechain --target ethers-v5 --out-dir src/types/other './node_modules/@uniswap/swap-router-contracts/artifacts/contracts/**/*.json'

> @uniswap/smart-order-router@2.5.30 compile-v2-types
> npx typechain --target ethers-v5 --out-dir src/types/v2 './node_modules/@uniswap/?(v2-core|v2-periphery)/build/*UniswapV2*.json'

'v3-periphery)' is not recognized as an internal or external command,
operable program or batch file.
'v2-periphery)' is not recognized as an internal or external command,
operable program or batch file.
ERROR: "compile-v3-types" exited with 255.

![image](https://user-images.githubusercontent.com/12429569/175775558-c9a50a58-15ce-401f-be5c-0b9814051f3e.png)

**Comment by vsharm29** [comment]
I am getting the same error. Please help

**Comment by tausif-bi** [comment]
yes i am on man and i did ran "npm install" before "npm run build"

**Comment by zhongeric** [comment]
What OS / version are you on?

**Comment by femanso** [comment]
I'm getting the same error on a clean clone of the repo. 
I'm using windows

**Comment by zhongeric** [comment]
This is likely an issue with the way the regex string is interpreted in windows vs. mac / linux distros. Looking into it

**Comment by zhongeric** [comment]
@femanso could you pull the new branch `fix-npm-scripts-windows` (https://github.com/Uniswap/smart-order-router/tree/fix-npm-scripts-windows) and try re-running `npm build` and let me know if the error persists?

**Comment by michaeljqzq** [comment]
> fix-npm-scripts-windows

Thanks, tried and it works!

**Comment by tausif-bi** [comment]
Yes I ran Npm install

Sent from my iPhone

On 29-Jun-2022, at 9:06 PM, Eric Zhong ***@***.***> wrote:

﻿

Are you on main and did you run npm install before npm run build?

**Comment by burgossrodrigo** [comment]
Tryed everything. The only thing that worked was running the build inside wsl.
