### ISSUE TITLE
Celo-Alfajores integration tests

### ISSUE THREAD

**Issue by raghava-pamula** [Uniswap/smart-order-router#104]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Celo-alfajores integration test is failing only for WCELO -> ERC20 Exact Input. Seemingly the cause is the RPC call is returning an error. 
<img width="1438" alt="Screen Shot 2022-06-29 at 11 10 14 PM" src="https://user-images.githubusercontent.com/106625855/176584630-911e241f-43d1-4c75-8a52-fc83073dd1b0.png">
<img width="1438" alt="Screen Shot 2022-06-29 at 11 10 40 PM" src="https://user-images.githubusercontent.com/106625855/176584669-45b0844d-84ac-4de6-859d-211b1ef65896.png">

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by zhongeric** [comment]
Resolved offline as needing to increase `jest.retries(1)` to account for flaky tests from other providers
