### ISSUE TITLE
Npm run build error after installing dependencies

### ISSUE THREAD

**Issue by sunny0714** [Uniswap/smart-order-router#174]
- **I'm submitting a bug report**

- **Summary**
I got not getting types error when executing "npm run build"

- **Result**
![image](https://user-images.githubusercontent.com/5579669/194567343-46c3231b-5630-47b1-b03b-211ffa20a106.png)

Please help with this

Thanks

**Comment by sunny0714** [comment]
Seems when installing dependencies, necessary artifacts are not included for generating types.
Especially in Uniswap package

**Comment by sunny0714** [comment]
Any advice?

**Comment by sunny0714** [comment]
Found why, there was [same issue](https://github.com/Uniswap/smart-order-router/issues/149)

**Comment by bilalhassan555** [comment]
Hey,

I am experiencing the same error while running `npm run build`. Can anyone help on this? @justindomingue @timnugent @NoahZinsmeister @grabbou @zhongeric
