### ISSUE TITLE
How to get data for testnet?

### ISSUE THREAD

**Issue by sytdas** [Uniswap/smart-order-router#196]
- **I'm submitting a ...**
  [x] question about how to use this project

- **Summary**
The `cloudflare-ipfs` url only host mainnets data. How can I get data of testnet like Goerli?
```ts
          new URISubgraphProvider(
            chainId,
            `https://cloudflare-ipfs.com/ipns/api.uniswap.org/v1/pools/v2/${chainName}.json`,
            undefined,
            0
          )
```
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by zhongeric** [comment]
You should be able to provide your own subgraph, or disable the subgraph to use the `staticSubgraphProvider` only
