### ISSUE TITLE
swap+add: complete iterative search for scenarios where first returned swap does not return expected ratio

### ISSUE THREAD

**Issue by ewilz** [Uniswap/smart-order-router#2]
Define error tolerance for ratio post-swap.
If post-swap ratio is not within error tolerance, retry search with market rate from first search (which likely didn't match up with expectations)
Alternatively, the swap may have moved sqrtPrice of the target pool, which in turn could push the post-swap ratio outside our error tolerance.

**Comment by willhennessy** [comment]
draft PR coming tomorrow

**Comment by ewilz** [comment]
https://github.com/Uniswap/smart-order-router/pull/6
