### ISSUE TITLE
Options to swap Exact ETH, and swap for Exact ETH

### ISSUE THREAD

**Issue by thanhnguyennguyen** [Uniswap/smart-order-router#208]
- **I'm submitting a question about how to use this project** 

- **Summary**
which Options to swap Exact ETH, and swap for Exact ETH ?

```
    let route = await router.route(
      CurrencyAmount.fromRawAmount(baseToken, baseAmount),
      quoteToken,
      TradeType.EXACT_INPUT,
      {
        type: SwapType.UNIVERSAL_ROUTER,
        recipient: myAddress,
        slippageTolerance: new Percent(1, 1000),
        deadlineOrPreviousBlockhash: Math.floor(Date.now() / 1000 + 300),
      }
    )
```
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by zhongeric** [comment]
To swap exact ETH, add this before your snippet
```
const baseToken = Ether.onChain(1) as Currency;
```
Swapping for exactETH (as output), use
```
const quoteToken = Ether.onChain(1) as Currency;
```

**Comment by thanhnguyennguyen** [comment]
Thank you so much @zhongeric

**Comment by s-pcode** [comment]
Hi @zhongeric 

`const baseToken = Ether.onChain(1) as Currency;` - this Ether.onChain() is not working for other chain native tokens. 

For example if the chain is Binance smart chain with chainId as 56, then it throws the below error : `Error: Invariant failed: WRAPPED`. I guess the WETH9 function is failing internally.

I'm able to get the quote for an erc20->erc20 pair using this sdk but not for a native token -> erc20. Below is my code implementation, please let me know if I have messed up somewhere.

```
 const router = new AlphaRouter({
      chainId,
      provider,
    });

    try {
      console.log(WETH9[chainId], "WETH9[chainId].address");
      const tokenA =
        tokenIn.token_address.toLowerCase() === getChainWiseNativeToken(chainId)
          ? (Ether.onChain(chainId) as Currency)
          : new Token(
              chainId,
              tokenIn.token_address,
              +tokenIn.decimals,
              tokenIn.symbol,
              tokenIn.symbol
            );
      const tokenB = new Token(
        chainId,
        tokenOut.address,
        tokenOut.decimals,
        tokenOut.symbol,
        tokenOut.name
      );

      const amountIn = CurrencyAmount.fromRawAmount(
        tokenA,
        JSBI.BigInt(ethers.utils.parseUnits(amount.toString(), tokenA.decimals))
      );

      console.log(amountIn.toExact(), "amountIn");

      let swapOptions: SwapOptions = {
        type: SwapType.UNIVERSAL_ROUTER,
        recipient: userWalletAddress,
        slippageTolerance: new Percent(5, 100),
        deadlineOrPreviousBlockhash: parseDeadline(360),
      };

      const partialRoutingConfig: Partial<AlphaRouterConfig> = {
        protocols: [Protocol.V2, Protocol.V3, Protocol.MIXED],
      };

      if (permitSig?.signature) {
        swapOptions = {
          ...swapOptions,
          inputTokenPermit: {
            ...permitSig?.permit,
            signature: permitSig.signature,
          },
        };
      }

      const quote = await router.route(
        amountIn,
        tokenB,
        TradeType.EXACT_INPUT,
        swapOptions,
        partialRoutingConfig
      );

      console.log(
        quote?.methodParameters?.calldata,
        "quote?.methodParameters?.calldata"
      );
      if (!quote) return;
      return quote;
    } catch (err: any) {
      console.log(err);
    }
```

**Comment by hubuyt001** [comment]
> * **I'm submitting a question about how to use this project**
> * **Summary**
>   which Options to swap Exact ETH, and swap for Exact ETH ?
> 
> ```
>     let route = await router.route(
>       CurrencyAmount.fromRawAmount(baseToken, baseAmount),
>       quoteToken,
>       TradeType.EXACT_INPUT,
>       {
>         type: SwapType.UNIVERSAL_ROUTER,
>         recipient: myAddress,
>         slippageTolerance: new Percent(1, 1000),
>         deadlineOrPreviousBlockhash: Math.floor(Date.now() / 1000 + 300),
>       }
>     )
> ```
> 
> * **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Can you post the complete code for swapping eth to usdc? It is easy to get confused because there are many classes with the same name in various SDKs.

**Comment by hubuyt001** [comment]
> Hi @zhongeric
> 
> `const baseToken = Ether.onChain(1) as Currency;` - this Ether.onChain() is not working for other chain native tokens.
> 
> For example if the chain is Binance smart chain with chainId as 56, then it throws the below error : `Error: Invariant failed: WRAPPED`. I guess the WETH9 function is failing internally.
> 
> I'm able to get the quote for an erc20->erc20 pair using this sdk but not for a native token -> erc20. Below is my code implementation, please let me know if I have messed up somewhere.
> 
> ```
>  const router = new AlphaRouter({
>       chainId,
>       provider,
>     });
> 
>     try {
>       console.log(WETH9[chainId], "WETH9[chainId].address");
>       const tokenA =
>         tokenIn.token_address.toLowerCase() === getChainWiseNativeToken(chainId)
>           ? (Ether.onChain(chainId) as Currency)
>           : new Token(
>               chainId,
>               tokenIn.token_address,
>               +tokenIn.decimals,
>               tokenIn.symbol,
>               tokenIn.symbol
>             );
>       const tokenB = new Token(
>         chainId,
>         tokenOut.address,
>         tokenOut.decimals,
>         tokenOut.symbol,
>         tokenOut.name
>       );
> 
>       const amountIn = CurrencyAmount.fromRawAmount(
>         tokenA,
>         JSBI.BigInt(ethers.utils.parseUnits(amount.toString(), tokenA.decimals))
>       );
> 
>       console.log(amountIn.toExact(), "amountIn");
> 
>       let swapOptions: SwapOptions = {
>         type: SwapType.UNIVERSAL_ROUTER,
>         recipient: userWalletAddress,
>         slippageTolerance: new Percent(5, 100),
>         deadlineOrPreviousBlockhash: parseDeadline(360),
>       };
> 
>       const partialRoutingConfig: Partial<AlphaRouterConfig> = {
>         protocols: [Protocol.V2, Protocol.V3, Protocol.MIXED],
>       };
> 
>       if (permitSig?.signature) {
>         swapOptions = {
>           ...swapOptions,
>           inputTokenPermit: {
>             ...permitSig?.permit,
>             signature: permitSig.signature,
>           },
>         };
>       }
> 
>       const quote = await router.route(
>         amountIn,
>         tokenB,
>         TradeType.EXACT_INPUT,
>         swapOptions,
>         partialRoutingConfig
>       );
> 
>       console.log(
>         quote?.methodParameters?.calldata,
>         "quote?.methodParameters?.calldata"
>       );
>       if (!quote) return;
>       return quote;
>     } catch (err: any) {
>       console.log(err);
>     }
> ```

Can you post the complete code for swapping eth to usdc? It is easy to get confused because there are many classes with the same name in various SDKs.

**Comment by s-pcode** [comment]
hey @hubuyt001 , i was facing something similar kind of issue last year too. Then I moved onto using the universal router which is much better and simpler for end users to swap tokens. Here is the [guide](https://saiprasadnayak.medium.com/uniswap-universal-router-integration-in-dapp-6f9fbb3e3886) which I wrote on it.

Hope this is helpful 👍

**Comment by hubuyt001** [comment]
Can you attach the github typescript code address of the complete demo?thank you

**Comment by hubuyt001** [comment]
As I said, different SDKs have the same name class, that is, the usage of different versions of the same SDK is also different


> hey @hubuyt001 , i was facing something similar kind of issue last year too. Then I moved onto using the universal router which is much better and simpler for end users to swap tokens. Here is the [guide](https://saiprasadnayak.medium.com/uniswap-universal-router-integration-in-dapp-6f9fbb3e3886) which I wrote on it.
> 
> Hope this is helpful 👍
Can you attach the github typescript code address of the complete demo?thank you
As I said, different SDKs have the same name class, that is, the usage of different versions of the same SDK is also different

**Comment by hubuyt001** [comment]
> hey @hubuyt001 , i was facing something similar kind of issue last year too. Then I moved onto using the universal router which is much better and simpler for end users to swap tokens. Here is the [guide](https://saiprasadnayak.medium.com/uniswap-universal-router-integration-in-dapp-6f9fbb3e3886) which I wrote on it.
> 
> Hope this is helpful 👍

I need to query the quotes between any two tokens, which may involve multiple pools. My input parameters are the mint addresses of the two tokens, find their quotes and then perform a swap

**Comment by yousufdigitalio** [comment]
> hey @hubuyt001 , i was facing something similar kind of issue last year too. Then I moved onto using the universal router which is much better and simpler for end users to swap tokens. Here is the [guide](https://saiprasadnayak.medium.com/uniswap-universal-router-integration-in-dapp-6f9fbb3e3886) which I wrote on it.
> 
> Hope this is helpful 👍

Can you please provide the github link with full source code?

**Comment by hubuyt001** [comment]
> To swap exact ETH, add this before your snippet
> 
> ```
> const baseToken = Ether.onChain(1) as Currency;
> ```
> 
> Swapping for exactETH (as output), use
> 
> ```
> const quoteToken = Ether.onChain(1) as Currency;
> ```
     const options: SwapOptionsSwapRouter02 = {
            recipient: walletAddress,
            slippageTolerance: percent,
            deadline: Math.floor(Date.now() / 1000 + 1800),
            type: SwapType.SWAP_ROUTER_02,
        }    can this swap eth to usdc directy ignore wrap weth and unwrap weth

**Comment by hubuyt001** [comment]
> > To swap exact ETH, add this before your snippet
> > ```
> > const baseToken = Ether.onChain(1) as Currency;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Swapping for exactETH (as output), use
> > ```
> > const quoteToken = Ether.onChain(1) as Currency;
> > ```
> 
> ```
 can this swap eth to usdc directy ignore wrap eth and unwrap weth
> ```

key codes 
  const router = new AlphaRouter({
            chainId: ChainId.MAINNET,
            provider: jsonRpcProvider,
        })
  const options: SwapOptionsSwapRouter02 = {
            recipient: walletAddress,
            slippageTolerance: percent,
            deadline: Math.floor(Date.now() / 1000 + 1800),
            type: SwapType.SWAP_ROUTER_02,
        }
 const route = await router.route(
            CurrencyAmount.fromRawAmount(
                inputToken,
                inputAmount
            ),
            outputToken,
            TradeType.EXACT_INPUT,
            options
        )
   const res = await sendTransaction(
        {
            data: route.methodParameters?.calldata,
            to: V3_SWAP_ROUTER_ADDRESS,
            value: route?.methodParameters?.value,
            from: walletAddress,
            maxFeePerGas: MAX_FEE_PER_GAS+MAX_PRIORITY_FEE_PER_GAS,
            maxPriorityFeePerGas: MAX_PRIORITY_FEE_PER_GAS,
        },
        provider,
        wallet
    )

export const V3_SWAP_ROUTER_ADDRESS =
  '0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45'
