### ISSUE TITLE
export 'ChainId' (imported as 'ChainId') was not found in '@uniswap/smart-order-router'

### ISSUE THREAD

**Issue by Rutvikghaskata** [Uniswap/smart-order-router#274]
I'm using @uniswap/widgets in reactjs and facing this issue - export 'ChainId' (imported as 'ChainId') was not found in '@uniswap/smart-order-router' 

Maybe this issue happens because @uniswap/smart-order-router package updated last 10 hour ago . 

![image](https://github.com/Uniswap/smart-order-router/assets/96057183/83ce15a7-b7e8-4dc5-8bf2-1ac29beab21b)

**Comment by MintCAD** [comment]
Same issue. Do i need to install smar-order-router package or is this a bug from uniswap end?

**Comment by lcrpt** [comment]
I have the same issue, did you found a solution ? 
Tried to downgrade version but still

**Comment by jsy1218** [comment]
Thanks for reporting the issue. We've added integration tests as part of our github workflow per pull request, so we expect to catch every compiling error in [smart-order-router](https://github.com/Uniswap/smart-order-router) repo.
