### ISSUE TITLE
Example variable `JSON_RPC_PROVIDER_BNB` should be `JSON_RPC_PROVIDER_BSC`

### ISSUE THREAD

**Issue by chrisckwong821** [Uniswap/smart-order-router#279]
- **I'm submitting a ...**
  [X ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Example variable `JSON_RPC_PROVIDER_BNB` should be `JSON_RPC_PROVIDER_BSC`

**Comment by jsy1218** [comment]
Actually it should be `JSON_RPC_PROVIDER_BNB`. They rebranded to BNB https://www.coindesk.com/business/2022/02/15/binance-smart-chain-rebrands-to-bnb-chain/
