### ISSUE TITLE
Why Cannot find module '../types/v3'?

### ISSUE THREAD

**Issue by fjq8** [Uniswap/smart-order-router#30]
## Please help me 
- when i 「npm run test」 it have a bug --> Cannot find module '../types/v3'
> Thank you very much

**Comment by JasonFenng** [comment]
same problem, who can help us?

**Comment by sabbathist** [comment]
> same problem, who can help us?

npm run build?

**Comment by ymmmmmmmm** [comment]
same problem, who can help us?

**Comment by willpote** [comment]
Make sure you have run npm install and npm run build before running the unit tests

Updated the README here: https://github.com/Uniswap/smart-order-router/commit/f082067ffb0e4b4ef498f6de6d81318587b3d427
