### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by JPSCHELE** [Uniswap/smart-order-router#301]
I'm submitting a ...
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Summary

Hi,
I've encountered a critical dependency issue related to the usage of OpenZeppelin contracts (version <=4.9.1) within the smart-contract router. Several vulnerabilities have been identified, and I believe it's essential to address these to ensure the security and stability of the project.
Other information

Vulnerabilities Detected:
SignatureChecker may revert on invalid EIP-1271 signers. [Details](https://github.com/advisories/GHSA-4g63-c64m-25w9)
GovernorVotesQuorumFraction updates to quorum may affect past defeated proposals. [Details](https://github.com/advisories/GHSA-xrc4-737v-9q75)
ERC165Checker may revert instead of returning false. [Details](https://github.com/advisories/GHSA-qh9x-gcfh-pcrw)
Vulnerable to ECDSA signature malleability. [Details](https://github.com/advisories/GHSA-4h98-2769-gh6h)
Cross-chain utilities for Arbitrum L2 see EOA calls as cross-chain calls. [Details](https://github.com/advisories/GHSA-9j3m-g383-29qr)
TransparentUpgradeableProxy clashing selector calls may not be delegated. [Details](https://github.com/advisories/GHSA-mx2q-35m2-x2rh)
GovernorCompatibilityBravo may trim proposal calldata. [Details](https://github.com/advisories/GHSA-93hq-5wgc-jc82)
Governor proposal creation may be blocked by frontrunning. [Details](https://github.com/advisories/GHSA-5h3x-9wvq-w4m2)
Using MerkleProof multiproofs may allow proving arbitrary leaves for specific trees. [Details](https://github.com/advisories/GHSA-wprv-93r4-jj2p)
ERC165Checker unbounded gas consumption. [Details](https://github.com/advisories/GHSA-7grf-83vw-6f5x)
Suggested Fix: The npm audit fix --force command suggests installing @uniswap/smart-order-router@2.0.1, which is a breaking change.
Affected Modules: The issue affects multiple modules, including @uniswap/smart-order-router, @uniswap/universal-router-sdk, @uniswap/v3-periphery, @uniswap/v3-staker, and others.
Impact: These vulnerabilities may lead to unexpected behavior, security risks, and potential loss of funds for users interacting with the affected contracts.
Recommendation: I strongly recommend reviewing the identified vulnerabilities and updating the dependencies to secure versions. Coordination with the OpenZeppelin team and other affected projects may also be beneficial.
Please let me know if you need any further information or assistance in resolving this issue.

**Comment by zhongeric** [comment]
Hi, thanks for opening this issue. We're aware of the vulnerabilities listed in previous versions of OZ contracts. However, we don't use any contracts that interface with the vulnerable contracts listed.
