### ISSUE TITLE
uniswap/smart-order-router

### ISSUE THREAD

**Issue by cing01** [Uniswap/smart-order-router#322]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by cing01** [comment]
None yet

**Comment by cing01** [comment]
wallet address 
0xC5518FC9eDEde9A9e1Fc37A8eCB3192fEA65126A

**Comment by jsy1218** [comment]
Can you give more details on what's the issue?

**Comment by cing01** [comment]
yes
