### ISSUE TITLE
Token1Balance.currency.wrapped returning Undefined

### ISSUE THREAD

**Issue by polishthunder** [Uniswap/smart-order-router#44]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X ] question about how to use this project

- **Summary**
I am trying to use the routeToRatio() function in AlphaRouter and I am following the steps given in the SDK guide. I receive this error when trying WETH and USDC pool on mainnet..

""if (token1Balance.currency.wrapped.sortsBefore(token0Balance.currency.wrapped)) {
                          ^
TypeError: Cannot read properties of undefined (reading 'currency')
    at AlphaRouter.routeToRatio (/Users/adrian/Documents/ARC/node_modules/@uniswap/smart-order-router/build/main/src/routers/alpha-router/alpha-router.js:148:27)""
 
To get the token1Balance/token0Balance I am using CurrencyAmount.fromRawAmount() and when I print the Token object returned by this function I see there is no ".wrapped" property, similar to what the error says. Also, when I print token1Balance.currency.wrapped, I receive the Token object, NOT undefined like the error would suggest. I am not sure why I would receive a valid value on my local machine but not once the token1Balance variable is sent to the SDK. I also have tried using parseAmount() as used in the alphaRouter test files but I get the same errors. I have run out of ideas of parameters to change or functions to try, any guidance on this problem would be greatly appreciated. 

Here is my code:

  const slot0 = await ETH_USDC_MAIN_30.methods.slot0().call();
  const feeTier = await ETH_USDC_MAIN_30.methods.fee().call();
 
  const liquidity = await ETH_USDC_MAIN_30.methods.liquidity().call();
  

  const token0 = await ETH_USDC_MAIN_30.methods.token0().call();
  const token1 = await ETH_USDC_MAIN_30.methods.token1().call();

  let TokenA = new Token(1, token0, 6 , USDC);

  console.log("Token A ", TokenA.wrapped);

  const TokenB = new Token(1, WETH_Address_Main, 18, "WETH", "Wrapped Ether");
  console.log("Token B ", TokenB.wrapped);

  

  const token0Balance =  CurrencyAmount.fromRawAmount(TokenA, "1000000000000000000");
  // const token0Balance = parseAmount("1000000000000000000", WETH_ethers);
  console.log("TOken 0 balance ", token0Balance);

  const token1Balance =   CurrencyAmount.fromRawAmount(TokenB, "1000000000000000000000");
  // const token1Balance = parseAmount("20", TokenB);
  console.log("TOken 1 balance ", token1Balance);

  const routeToRatioResponse = await router.routeToRatio({
    token0Balance: token0Balance,
    token1Balance: token1Balance,
    position: await new Position({
      pool: await new Pool(
        TokenA,
        TokenB,
        Number(feeTier),
        slot0.sqrtPriceX96.toString(),
        liquidity,
        Number(slot0.tick),

      ),
      tickLower: Number("193380"),
      tickUpper: Number("203160"),
      liquidity: 1, //leave as 1
     }),

**Comment by polishthunder** [comment]
`const tokenIn = currencyIn.wrapped;
                                   ^

TypeError: Cannot read properties of undefined (reading 'wrapped')
    at AlphaRouter.route (/Users/adrian/Documents/ARC/node_modules/@uniswap/smart-order-router/build/main/src/routers/alpha-router/alpha-router.js:266:36)`

Receiving the same error when trying the .route() function of the AlphaRouter. The SDK asks for a CurrencyAmount**.wrapped** but neither the token1Balance or the currencyIn have a .wrapped property. Doesnt seem that any CurrencyAmount does. What is being asked for by the .wrapped property?

**Comment by AceLuodan** [comment]
i also meets this error，anyone who can help？

**Comment by polishthunder** [comment]
@AceLuodan 
This error occurs when you try to send the AlphaRouter instance an object {}, instead of a series of variables. This code worked for me. Notice the variables are not wrapped in an object{}, but only separated by commas. The clue in the guide example was that there was only one "{" in the .routeToRatio() example code.

`let response = await router.routeToRatio(
       token0Balance,
       token1Balance,
      position,
       {
        ratioErrorTolerance: new Fraction(1, 100),
        maxIterations: 6,
      },
      {
        addLiquidityOptions: {
          // recipient: recipient,
          tokenId:24041,
          // recipient: "0x0000000000000000000000000000000000000001",
        },
        swapOptions: {
          deadline: deadline,
          recipient:recipient,
          slippageTolerance: new Percent(5, 10000),
        },
      },

    );
`

**Comment by polishthunder** [comment]
`.currency.wrapped.`

**Comment by polishthunder** [comment]
When I call `.currency.wrapped` on the `CurrencyAmount` object, it would return the `.currency` object. 

I actually figured it out after looking at those tests and the Routing-API (https://github.com/Uniswap/routing-api) quote calls. My error was passing the routeToRatio() function an object{} instead of a series of variables. It works for me now, as described in my comment to AceLuodan. Thanks for the response though.
