### ISSUE TITLE
How to run it as an api? 

### ISSUE THREAD

**Issue by hoangphuong24984** [Uniswap/smart-order-router#56]
ex:
https://localhost:3000/api/quote?protocols=v2%2Cv3&tokenInAddress=0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270&tokenInChainId=137&tokenOutAddress=0xD6DF932A45C0f255f85145f286eA0b292B21C90B&tokenOutChainId=137&amount=10000000000000000000000&type=exactIn

**Comment by willpote** [comment]
This package contains no code for running as an API. The code we use to deploy as an API is in [Uniswap/routing-api](https://github.com/Uniswap/routing-api), and uses AWS. If you want localhost you will need to build your own solution.

**Comment by willpote** [comment]
Closing, feel free to reopen if you have more questions
