### ISSUE TITLE
Where does the JSBI package come from?

### ISSUE THREAD

**Issue by brankomiric-cw** [Uniswap/smart-order-router#63]
- **I'm submitting a ...**
  [ x] question about how to use this project

- **Summary**

Hey can you update your example from your official docs? https://docs.uniswap.org/sdk/guides/auto-router. You are using JSBI.BigInt in the example, but you aren't importing JSBI. What JSBI is this? If I install the one from npm, typescript compiler doesn't like it.

**Comment by ahmetgeymen** [comment]
I think JSBI should come from @uniswap/sdk-core. It currently resolves to version 3.2.5. Installing versions over 4.0.0 emerges another problems.

```json
  "dependencies": {
    "@ethersproject/address": "^5.0.2",
    "big.js": "^5.2.2",
    "decimal.js-light": "^2.5.0",
    "jsbi": "^3.1.4",
    "tiny-invariant": "^1.1.0",
    "toformat": "^2.0.0"
  }
```


https://github.com/Uniswap/sdk-core/blob/76b41d349ef7f9e0555383b1b11f95872e91e975/package.json#L27

**Comment by hensha256** [comment]
Yes JSBI is being brought in as a peer dependency. Currently we only support v3 and not v4, though we are considering updating this in future - e.g. [see this issue](https://github.com/Uniswap/v3-sdk/issues/133)

For now you must use JSBI V3 - the latest of which is v3.2.5. We are adding this as an explicit peer dependency in PR #169 to make it clearer to our users.

Sorry for the confusion!

**Comment by ChadwickAChauncey** [comment]
https://github.com/Uniswap/sdk-core/blob/76b41d349ef7f9e0555383b1b11f95872e91e975/package.json#L27
