### ISSUE TITLE
Different swap routes for EXACT_OUTPUT vs EXACT_INPUT

### ISSUE THREAD

**Issue by yodlmeister** [Uniswap/smart-order-router#642]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

The router suggests wildly different routes depending on TradeType: `EXACT_OUTPUT` vs `EXACT_INPUT`.

The routes for `EXACT_OUTPUT` are particularly inefficient.

Example output comparing the two modes:

```
* EXACT_OUTPUT route
[V3] 100.00% = FRAX -- 0.3% [0x49..B9] --> ARB -- 1% [0x7F..c1] --> DAI

* EXACT_INPUT route
[V3] 100.00% = FRAX -- 0.05% [0x1E..22] --> USDT -- 0.01% [0x7f..a9] --> DAI
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Sample code to reproduce:
https://github.com/yodlmeister/smart-order-router-bug

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID xds8903, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)

**Comment by yodlmeister** [comment]
Solved by using the `parseAmount` method.
