### ISSUE TITLE
routeToRatio() throws error 'Could not parse fraction' when output balance is zero.

### ISSUE THREAD

**Issue by eliotstock** [Uniswap/smart-order-router#65]
- **I'm submitting a ...**
  [*] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Consider a "swap and add liquidity" transaction using the alpha router where the account has some WETH, some ETH for gas, and no USDC. I want to add liquidity to the WETH/USDC pool, for which I need to first swap about half my WETH to USDC (because my range happens to straddle the current price in the pool pretty evenly).

Calling `AlphaRouter.routeToRatio()` and passing in a token1Balance of zero USDC will result in this line in the stack...

https://github.com/Uniswap/smart-order-router/blob/b19ebcb3f3e2b6b10a8021884f5336c8735ba8a5/src/routers/alpha-router/functions/calculate-ratio-amount-in.ts#L12

... throwing an error 'Could not parse fraction'. Multiplying a `Fraction` by a `CurrencyAmount` (both from `sdk-core`) that is zero throws the error.

My stack trace is:

```
/home/e/r/dro/smart-order-router/node_modules/@uniswap/sdk-core/src/entities/fractions/fraction.ts:38
    throw new Error('Could not parse fraction')
          ^
Error: Could not parse fraction
    at Function.tryParseFraction (/home/e/r/dro/smart-order-router/node_modules/@uniswap/sdk-core/src/entities/fractions/fraction.ts:38:11)
    at Fraction.multiply (/home/e/r/dro/smart-order-router/node_modules/@uniswap/sdk-core/src/entities/fractions/fraction.ts:108:34)
    at Object.calculateRatioAmountIn (/home/e/r/dro/smart-order-router/src/routers/alpha-router/functions/calculate-ratio-amount-in.ts:18:60)
    at AlphaRouter.routeToRatio (/home/e/r/dro/smart-order-router/src/routers/alpha-router/alpha-router.ts:613:26)
    at DRO.<anonymous> (/home/e/r/dro/dro/src/dro.ts:700:70)
    at step (/home/e/r/dro/dro/src/dro.ts:33:23)
    at Object.next (/home/e/r/dro/dro/src/dro.ts:14:53)
    at fulfilled (/home/e/r/dro/dro/src/dro.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'd expect this to be quite a common starting state for the account - some of one asset and none of the other in the pool. The SDK docs at https://docs.uniswap.org/sdk/guides/liquidity/swap-and-add use an example with some USDC but no WETH. Nevertheless, could it be that there are no tests that cover this scenario?

**Comment by hensha256** [comment]
I believe this is a duplicate issue of #64. Closing this one as that one has a more detailed breakdown

**Comment by kelvinjess203** [comment]
Hi , as i checking , please update these file:
file: 
useWrapCallback
![image](https://user-images.githubusercontent.com/49341466/201710569-81aa4243-ed19-4b00-be72-9e6b9226aada.png)
becase, you are lessThan a Class CurrencyAmount, but we need check with class Fraction

sorting ( use for currencySearchModal )
![image](https://user-images.githubusercontent.com/49341466/201711490-7d50b6e8-fb80-4bd8-bb2a-16f4d68b7802.png)

or update your try update like this
![image](https://user-images.githubusercontent.com/49341466/201712294-12d8872f-c451-4e02-8da7-31d8d92cec9b.png)
