### ISSUE TITLE
Unable to validate token SHINJA 

### ISSUE THREAD

**Issue by rileyg98** [Uniswap/smart-order-router#66]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Upon trying to calculate a route to swap WETH to Holdenomics or Para Token, we have found that in the routers attempts to find a route, it fails to validate the SHINJA contract during route calculation and fails to return a route. 
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
I've attached a debug trace of the swap with holdenomics - the same occurs on Para.
[debug.txt](https://github.com/Uniswap/smart-order-router/files/8087444/debug.txt)

**Comment by rileyg98** [comment]
I have determined that both tokens have currently got a 0% buy tax, and this may be the common link.

**Comment by rileyg98** [comment]
It appears this is related to #59 - shinja fails to validate, so it considers the token we're swapping for invalid (as opposed to just the shinja pair)

**Comment by rileyg98** [comment]
After further testing it appears if a possible route is not validated successfully, the whole pair is thrown out. Shinja appears to need too much gas in this instance to run a loan or swap. 

After upping the gas per validate to 600k, we successfully get a quote.

**Comment by willpote** [comment]
Thank you for diving into this. I put in a fix here: https://github.com/Uniswap/smart-order-router/commit/c01f48a5b785a9aa4910e37002156f12adaf7e97

And Shinja can now be swapped
