### ISSUE TITLE
subgraph for arbitrum-rinkeby

### ISSUE THREAD

**Issue by coin77** [Uniswap/smart-order-router#69]
Would it be possible to get a supgraph on 

https://cloudflare-ipfs.com/ipns/api.uniswap.org/v1/pools/v3/

for arbitrum-rinkeby?

**Comment by willpote** [comment]
Unfortunately theres no subgraph set up for Uniswap on arbitrum rinkeby currently. You can override the subgraph providers to use the 'StaticSubgraphProvider' when you create the AlphaRouter object:

https://github.com/Uniswap/smart-order-router/blob/main/src/providers/v3/static-subgraph-provider.ts
https://github.com/Uniswap/smart-order-router/blob/main/src/providers/v2/static-subgraph-provider.ts
