### ISSUE TITLE
ProviderGasError

### ISSUE THREAD

**Issue by DerekYeung** [Uniswap/smart-order-router#80]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [V] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I got ProviderGasError from my own node, I saw the same issue in #10 , but Im not sure what configuration of node should i change

**Comment by riordant** [comment]
Hi @DerekYeung , had the same problem today.
if you are running Geth/Erigon, you need to provide a command line argument - `rpc.gascap {LIMIT}`. For a `LIMIT` value of 150m, it should work. For Erigon, you can pass 0 to allow unlimited size.

**Comment by DerekYeung** [comment]
@riordant Hey thanks! I used to set gascap to 0 but it didn't work, but now it works with 150m, btw do you know why it so slow? It seems to take a few seconds on each quote even on node server

I tried another lib https://www.npmjs.com/package/simple-uniswap-sdk it's fast, 400-600ms in each quote, but the data has some difference, not 100% accurate

**Comment by James1847** [comment]
> Hi @DerekYeung , had the same problem today. if you are running Geth/Erigon, you need to provide a command line argument - `--rpc.gascap {LIMIT}`. For a `LIMIT` value of 150m, it should work. For Erigon, you can pass 0 to allow unlimited size.

Hi, I want to know the 150m means how much with exactly number ? 150m == 150000000

**Comment by relayxderek** [comment]
yes 150m = 150000000

**Comment by DerekYeung** [comment]
> > Hi @DerekYeung , had the same problem today. if you are running Geth/Erigon, you need to provide a command line argument - `--rpc.gascap {LIMIT}`. For a `LIMIT` value of 150m, it should work. For Erigon, you can pass 0 to allow unlimited size.
> 
> Hi, I want to know the 150m means how much with exactly number ? 150m == 150000000

yes

**Comment by willpote** [comment]
Thanks for the discussion all, I've updated our readme with this information here: https://github.com/Uniswap/smart-order-router/pull/129

 Closing
